from app.services.auth_service import (
    register_user,
    authenticate_user,
    create_token_response,
    refresh_access_token,
    send_verification_code,
    verify_phone_code,
    change_user_password,
    update_user_profile,
    get_user_by_id,
    _build_user_response,
)

from app.services.product_service import (
    get_category_tree,
    get_category_by_id,
    get_category_by_slug,
    create_category,
    update_category,
    delete_category,
    get_all_categories_flat,
    get_all_brands,
    get_brand_by_id,
    create_brand,
    search_products,
    search_products_net,
    get_brand_facets,
    get_category_price_range,
    get_product_by_id,
    get_product_by_slug,
    create_product,
    update_product,
    delete_product,
    increment_product_view,
    get_related_products,
    get_products_by_category,
    get_featured_products,
    get_new_products,
    get_best_selling_products,
    _build_product_list_response,
)

from app.services.identity_service import (
    get_users_paginated,
    get_user_by_id,
    create_user,
    update_user,
    soft_delete_user,
    assign_role_to_user,
    get_roles_with_counts,
    get_role_by_id,
    create_role,
    update_role,
    soft_delete_role,
    get_role_claims_with_relations,
    get_role_claim_by_id,
    create_role_claim,
    update_role_claim,
    soft_delete_role_claim,
    get_user_roles_with_relations,
    get_user_role_by_id,
    create_user_role,
    update_user_role,
    soft_delete_user_role,
    get_identity_infos_with_user,
    get_identity_info_by_id,
    create_identity_info,
    update_identity_info,
    accept_identity_info,
    reject_identity_info,
    soft_delete_identity_info,
)

from app.services.order_service import (
    get_cart,
    save_cart,
    enrich_cart_with_products,
    get_pay_methods,
    get_post_types,
    validate_discount_code,
    calculate_discount_value,
    create_order,
    update_order_status,
    get_order_by_id,
    get_user_orders,
    get_all_orders,
    build_order_response,
)

from app.services.payment_service import ZarinPalGateway
from app.services.sms_service import SelectedSmsSender, FarazSmsSender, MelipayamakSmsSender, BaleSmsSender
from app.services.email_service import EmailSender

__all__ = [
    # Auth
    "register_user",
    "authenticate_user",
    "create_token_response",
    "refresh_access_token",
    "send_verification_code",
    "verify_phone_code",
    "change_user_password",
    "update_user_profile",
    "get_user_by_id",
    "_build_user_response",

    # Categories
    "get_category_tree",
    "get_category_by_id",
    "get_category_by_slug",
    "create_category",
    "update_category",
    "delete_category",
    "get_all_categories_flat",

    # Brands
    "get_all_brands",
    "get_brand_by_id",
    "create_brand",

    # Products
    "search_products",
    "search_products_net",
    "get_brand_facets",
    "get_category_price_range",
    "get_product_by_id",
    "get_product_by_slug",
    "create_product",
    "update_product",
    "delete_product",
    "increment_product_view",
    "get_related_products",
    "get_products_by_category",
    "get_featured_products",
    "get_new_products",
    "get_best_selling_products",
    "_build_product_list_response",

    # Cart & Orders
    "get_cart",
    "save_cart",
    "enrich_cart_with_products",
    "get_pay_methods",
    "get_post_types",
    "validate_discount_code",
    "calculate_discount_value",
    "create_order",
    "update_order_status",
    "get_order_by_id",
    "get_user_orders",
    "get_all_orders",
    "build_order_response",
]